// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Scraper;

namespace Bundeswort.Migrations
{
    [DbContext(typeof(VideosDbContext))]
    [Migration("20201011133731_UnaccentExtension")]
    partial class UnaccentExtension
    {
    }
}
